DROP DATABASE IF EXISTS Webbit;

CREATE DATABASE Webbit;

USE Webbit;

CREATE TABLE Roles (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  role VARCHAR(256) NOT NULL
); 

INSERT INTO `roles`(`id`, `role`) VALUES ('1','Member');

CREATE TABLE Users (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(16) NOT NULL UNIQUE,
  pwd VARCHAR(256) NOT NULL,
  email VARCHAR(256) NOT NULL,
  karmapoints INT NOT NULL DEFAULT 0,
  description VARCHAR(256) NULL,
  country VARCHAR(256) NULL,
  role_id INT NOT NULL DEFAULT 1,
  created_in DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (role_id) REFERENCES Roles(id)
); 

CREATE TABLE Category (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(16) NOT NULL
); 

CREATE TABLE Posts (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(50) NOT NULL,
  text LONGTEXT NOT NULL,
  user_id INT NOT NULL,
  karmapoints INT NULL,
  category_id INT NOT NULL,
  created_in DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES Users(id),
  FOREIGN KEY (category_id) REFERENCES Category(id)
); 

CREATE TABLE Comments (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  text LONGTEXT NOT NULL,
  karmapoints INT NULL,
  user_id INT NOT NULL,
  post_id INT NOT NULL,
  created_in DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES Users(id),
  FOREIGN KEY (post_id) REFERENCES Posts(id)
); 
